# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeRhFHG_PHv2Q3nc1mH4xvPZ4fmH24_t
"""

from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route("/chatbot", methods=["POST"])
def chatbot_response():
    try:
        data = request.get_json()

        # Handle missing 'message' key
        if not data or "message" not in data:
            return jsonify({"error": "Invalid request. Please provide a 'message' field."}), 400

        user_input = data["message"].strip().lower()  # Convert to lowercase for case insensitivity

        # Basic symptom response logic
        if "fever" in user_input:
            response = "You might have the flu. Please monitor your temperature."
        elif "headache" in user_input:
            response = "It could be a tension headache. Try to rest and stay hydrated."
        else:
            response = "I'm here to help. Can you describe your symptoms?"

        return jsonify({"response": response})

    except Exception as e:
        return jsonify({"error": str(e)}), 500  # Return a proper error message

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)  # Allow external access