# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1am9GYp4k7qgoFurJm4OJqKyNMoHq2Zwr
"""

from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk

# Download required resources
nltk.download('vader_lexicon')

# Initialize Sentiment Intensity Analyzer
sia = SentimentIntensityAnalyzer()

# Function to analyze mental health based on sentiment
def analyze_mental_health(user_text):
    score = sia.polarity_scores(user_text)

    if score["compound"] >= 0.05:
        return "Positive Mood"
    elif score["compound"] <= -0.05:
        return "Negative Mood"
    else:
        return "Neutral Mood"

# Example user input
user_mood = "I feel very stressed and anxious."
print("Mental Health Status:", analyze_mental_health(user_mood))