# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlzuiGW07b1_QW9iY_61F0h6rotb8egE
"""

import random

# Function to recommend diet based on disease
def recommend_diet(disease):
    diet_plans = {
        "Diabetes": ["Low-carb foods", "Fruits, Vegetables", "Avoid Sugar"],
        "Hypertension": ["Low-sodium diet", "More Potassium", "Less Processed Food"],
        "Obesity": ["Caloric deficit", "More fiber and protein", "Exercise regularly"]
    }
    return diet_plans.get(disease, ["Balanced Diet", "Stay Hydrated"])

# Function to recommend exercise based on disease
def recommend_exercise(disease):
    exercises = {
        "Diabetes": ["Walking", "Yoga", "Strength Training"],
        "Hypertension": ["Meditation", "Cardio", "Deep Breathing"],
        "Obesity": ["Running", "Swimming", "HIIT"]
    }
    return exercises.get(disease, ["30 min Daily Exercise"])

# Test with a diagnosed disease
diagnosed_disease = "Diabetes"
print("Recommended Diet:", recommend_diet(diagnosed_disease))
print("Recommended Exercise:", recommend_exercise(diagnosed_disease))
